[18.0][MIG] product_packaging_dimension: Migration to 18.0
LucasTran380381/product-attribute pull request #2
Opened 2024-10-23 11:00 UTC by LucasTran380381

No change code

2024-10-23 12:16 UTC, xaviedoanhduy requested changes
please also add a file `readme/CREDITS.md` or update existing one:
`The migration of this module from 17.0 to 18.0 was financially supported by Camptocamp.`

2024-10-23 12:16 UTC, xaviedoanhduy commented on product_packaging_dimension/models/product_packaging.py
> +        readonly=True,
```suggestion
```

> By default, related fields are:
> - not stored
> - not copied
> - readonly
> - computed in superuser mode

2024-10-23 12:16 UTC, xaviedoanhduy commented on product_packaging_dimension/models/product_packaging.py
> +        compute=False,
looks weird.
[:param str compute: name of a method that computes the field](https://github.com/odoo/odoo/blob/5628c232bddb958b6e446b9248bfd80cef998eb4/odoo/fields.py#L223)

2024-10-23 12:16 UTC, xaviedoanhduy commented on product_packaging_dimension/models/product_packaging.py
> +        readonly=True,
```suggestion
```
no need readonly attr on related field

2024-10-23 12:16 UTC, xaviedoanhduy commented on product_packaging_dimension/models/product_packaging.py
> +    volume = fields.Float(
```suggestion
    volume = fields.Float(
        digits=(8, 4),
        compute="_compute_volume",
        help="The Packaging volume",
    )
```

> computed fields are not stored by default, they are computed and returned when requested.
> Computed fields are readonly by default. To allow setting values on a computed field, use the inverse parameter.
detail in [Computed Fields](https://www.odoo.com/documentation/18.0/developer/reference/backend/orm.html#computed-fields)

2024-10-23 12:16 UTC, xaviedoanhduy commented on product_packaging_dimension/models/product_packaging.py
> +        readonly=True,
```suggestion
```
same all above.

2024-10-23 12:16 UTC, xaviedoanhduy commented on product_packaging_dimension/readme/CONTRIBUTORS.md
> +- Denis Roussel \<<denis.roussel@acsone.eu>\>
you can add your name in here. 
ex: Nhan Tran \<<nhant@trobz.com>\>

2024-10-23 12:18 UTC, xaviedoanhduy commented
btw, amend commit `init v18` following syntax `[MIG] $module: Migration to 18.0`

2024-10-24 02:44 UTC, LucasTran380381 commented on product_packaging_dimension/models/product_packaging.py
> +        compute=False,
Should I remove compute attr ?

2024-10-24 03:20 UTC, xaviedoanhduy commented on product_packaging_dimension/models/product_packaging.py
> +        compute=False,
you can, because it default value is `None`.
and it takes one argument which is a string specifying the function name, not a `truly or falsy` value

2024-10-24 04:11 UTC, xaviedoanhduy commented
![image](https://github.com/user-attachments/assets/40a87ec1-c2a0-432b-b6d6-9289ce585090)
should squash `[FIX] fix review points` into `[MIG] product_packaging_dimension: Migration to 18.0`

2024-10-24 04:13 UTC, xaviedoanhduy commented
> Squash administrative commits (if any) with the previous commit for reducing commit noise. Check https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate for details.

2024-10-24 04:23 UTC, LucasTran380381 commented
@xaviedoanhduy Hello Duy, I'm fixed squash commit

2024-10-24 04:29 UTC, xaviedoanhduy approved these changes
![image](https://github.com/user-attachments/assets/0248c3b6-09fa-4bf1-a655-5311f18f1e9a)
Overall, it looks fine to me.

2024-10-24 04:35 UTC, merged

2024-10-24 04:57 UTC, xaviedoanhduy commented
hi @LucasTran380381,
sorry for the noise, can you remove `readme/CREDITS.md` from the migration commit, 
thanks